"""
Week 7 — Autonomous Business Logic
A Startup Operations Agent for Zynxis: it reads a raw client brief and returns
a task breakdown, a dated delivery timeline, and a justified tech stack.

  brief.md ─► analyse ─► break down ─► validate ─► schedule ─► tech stack ─► plan
              (LLM)      (LLM)         (code)      (code)      (LLM)

The LLM decides what work exists and how big it is. The dates, the critical
path and the resource contention are computed in Python — see schedule.py.

Run modes:
  python ops_agent.py                              → the default sample brief
  python ops_agent.py --brief briefs/marketplace.md
  python ops_agent.py --start 2026-09-01 --team "Backend Engineer=2,QA Engineer=1"
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date, datetime

import schedule as sched
import stages

PLAN_MD   = "task_plan.md"
PLAN_JSON = "plan.json"
DEFAULT_BRIEF = "briefs/fintech_app.md"

DEFAULT_TEAM = {
    "Product Manager": 1,
    "UX Designer": 1,
    "Frontend Engineer": 2,
    "Backend Engineer": 2,
    "QA Engineer": 1,
    "DevOps Engineer": 1,
}

BOLD, CYAN, GREEN, YELLOW, RED, RESET = (
    "\033[1m", "\033[96m", "\033[92m", "\033[93m", "\033[91m", "\033[0m")


def parse_team(spec: str) -> dict[str, int]:
    """Parses 'Backend Engineer=2,QA Engineer=1' into a headcount map."""
    team: dict[str, int] = {}
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "=" not in part:
            raise ValueError(f"expected 'Role=count', got {part!r}")
        role, _, count = part.partition("=")
        team[role.strip()] = max(1, int(count))
    return team


def render_plan(analysis: dict, breakdown: dict, tasks: list[dict],
                stack: dict, summary: dict, repairs: list[str],
                team: dict[str, int]) -> str:
    epic_names = {e.get("id"): e.get("name", e.get("id"))
                  for e in breakdown.get("epics", [])}

    out: list[str] = [
        f"# Delivery Plan — {analysis.get('project_name', 'Untitled Project')}",
        "",
        "**Prepared by:** Zynxis Startup Operations Agent  ",
        f"**Generated:** {date.today():%d %B %Y}  ",
        f"**Planned start:** {summary['start']:%d %B %Y}  ",
        f"**Projected delivery:** {summary['end']:%d %B %Y}  ",
        f"**Duration:** {summary['duration_working_days']} working days "
        f"(~{summary['duration_weeks']} weeks)  ",
        f"**Total effort:** {summary['total_effort_days']} person-days across "
        f"{summary['task_count']} tasks  ",
        f"**Team:** {summary['headcount']} people — "
        + ", ".join(f"{n}× {r}" for r, n in sorted(team.items())),
        "",
        "> Dates are computed from the task graph, not generated by the language "
        "model: dependencies and per-role capacity are resolved in code, so the "
        "timeline is arithmetically consistent with the estimates above it.",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        analysis.get("summary", ""),
        "",
    ]

    if analysis.get("objectives"):
        out += ["**Business objectives**", ""]
        out += [f"- {o}" for o in analysis["objectives"]] + [""]

    # -- scope
    out += ["## Scope", "", "**In scope**", ""]
    out += [f"- {s}" for s in analysis.get("in_scope", [])] or ["- unspecified"]
    out += ["", "**Explicitly out of scope**", ""]
    out += [f"- {s}" for s in analysis.get("out_of_scope", [])] or ["- none stated"]
    out += [""]

    # -- open questions: the part a client actually needs to act on
    if analysis.get("open_questions"):
        out += ["## Open Questions", "",
                "These need client answers. Each shows the assumption the plan "
                "currently runs on, so the cost of a different answer is visible.",
                "",
                "| # | Question | Why it matters | Assumed for now |",
                "|---|---|---|---|"]
        for i, q in enumerate(analysis["open_questions"], 1):
            out.append(f"| {i} | {q.get('question','')} | {q.get('why_it_matters','')} "
                       f"| {q.get('assumption','')} |")
        out += [""]

    # -- risks
    if analysis.get("risks"):
        out += ["## Risks", "", "| Severity | Risk | Mitigation |", "|---|---|---|"]
        rank = {"high": 0, "medium": 1, "low": 2}
        for r in sorted(analysis["risks"], key=lambda x: rank.get(x.get("severity"), 3)):
            out.append(f"| {r.get('severity','?').upper()} | {r.get('risk','')} "
                       f"| {r.get('mitigation','')} |")
        out += [""]

    # -- task breakdown by epic
    out += ["## Task Breakdown", ""]
    for epic in breakdown.get("epics", []):
        epic_tasks = [t for t in tasks if t.get("epic") == epic.get("id")]
        if not epic_tasks:
            continue
        effort = sum(float(t.get("estimate_days", 0)) for t in epic_tasks)
        out += [f"### {epic.get('id')} — {epic.get('name', '')}", "",
                f"*{epic.get('goal', '')}*", "",
                f"{len(epic_tasks)} tasks · {effort:.0f} person-days", "",
                "| ID | Task | Role | Est. | Depends on | Start | End | Critical |",
                "|---|---|---|---|---|---|---|---|"]
        for t in epic_tasks:
            deps = ", ".join(t.get("depends_on", [])) or "—"
            out.append(
                f"| {t['id']} | {t.get('title','')} | {t.get('role','')} "
                f"| {t.get('estimate_days')}d | {deps} "
                f"| {t['start']:%d %b} | {t['end']:%d %b} "
                f"| {'yes' if t.get('critical') else ''} |"
            )
        out += [""]

    # -- timeline
    out += ["## Timeline", "",
            f"Critical path: **{summary['critical_task_count']} of "
            f"{summary['task_count']} tasks** have zero slack. Any slip on those "
            "moves the delivery date directly.", "",
            "| Task | Role | Start | End | Slack |", "|---|---|---|---|---|"]
    for t in sorted(tasks, key=lambda x: (x["start"], x["id"])):
        if t.get("critical"):
            out.append(f"| **{t['id']} {t.get('title','')}** | {t.get('role','')} "
                       f"| {t['start']:%d %b %Y} | {t['end']:%d %b %Y} | 0 |")
    out += ["",
            f"**Effort by role** — total {summary['total_effort_days']} person-days, "
            f"compressed into {summary['duration_working_days']} working days "
            f"({summary['parallelism']}× average parallelism).", "",
            "| Role | Person-days |", "|---|---|"]
    for role, days in summary["effort_by_role"].items():
        out.append(f"| {role} | {days} |")
    out += [""]

    # -- tech stack
    out += ["## Recommended Tech Stack", "",
            "| Layer | Choice | Why | Runner-up | Why not |", "|---|---|---|---|---|"]
    for rec in stack.get("recommendations", []):
        out.append(f"| {rec.get('layer','')} | **{rec.get('choice','')}** "
                   f"| {rec.get('rationale','')} | {rec.get('alternative','')} "
                   f"| {rec.get('why_not_alternative','')} |")
    out += [""]

    if stack.get("architecture_notes"):
        out += ["**Architecture**", ""] + [f"- {n}" for n in stack["architecture_notes"]] + [""]
    if stack.get("scaling_considerations"):
        out += ["**Scaling considerations**", ""] + \
               [f"- {n}" for n in stack["scaling_considerations"]] + [""]

    # -- audit trail
    out += ["## Plan Validation", ""]
    if repairs:
        out += [f"The scheduler rejected or repaired {len(repairs)} item(s) in the "
                "model's breakdown before computing dates:", ""]
        out += [f"- {r}" for r in repairs]
    else:
        out += ["The model's task graph passed validation with no repairs: all task "
                "ids unique, all dependencies resolvable, all estimates within range."]
    out += [""]

    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description="Startup Operations Agent.")
    parser.add_argument("--brief", default=DEFAULT_BRIEF, help="client brief markdown file")
    parser.add_argument("--start", help="project start date, YYYY-MM-DD (default: today)")
    parser.add_argument("--team", help="e.g. 'Backend Engineer=2,QA Engineer=1'")
    parser.add_argument("--out", default=PLAN_MD, help=f"output file (default: {PLAN_MD})")
    args = parser.parse_args()

    try:
        with open(args.brief, encoding="utf-8") as f:
            brief = f.read()
    except OSError as exc:
        sys.exit(f"{RED}could not read brief: {exc}{RESET}")

    start = (datetime.strptime(args.start, "%Y-%m-%d").date()
             if args.start else date.today())
    try:
        team = parse_team(args.team) if args.team else dict(DEFAULT_TEAM)
    except ValueError as exc:
        sys.exit(f"{RED}bad --team: {exc}{RESET}")

    print(f"\n{BOLD}Startup Operations Agent — Week 7{RESET}")
    print("=" * 70)
    print(f"Brief : {args.brief} ({len(brief.split())} words)")
    print(f"Start : {start:%d %B %Y}")
    print(f"Team  : {sum(team.values())} people")
    print("=" * 70)

    try:
        client = stages.build_client()

        print(f"\n{BOLD}[1/5]{RESET} Analysing the brief…")
        analysis = stages.analyse(client, brief)
        print(f"{GREEN}  {analysis.get('project_name','?')}{RESET} · "
              f"complexity {analysis.get('complexity','?')} · "
              f"{len(analysis.get('open_questions', []))} open questions · "
              f"{len(analysis.get('risks', []))} risks")

        print(f"\n{BOLD}[2/5]{RESET} Breaking down the work…")
        breakdown = stages.break_down(client, analysis)
        repairs = stages.validate_breakdown(breakdown)
        tasks = breakdown["tasks"]
        print(f"{GREEN}  {len(breakdown.get('epics', []))} epics · "
              f"{len(tasks)} tasks{RESET}")
        for r in repairs:
            print(f"{YELLOW}  repaired: {r}{RESET}")

        print(f"\n{BOLD}[3/5]{RESET} Scheduling (dependencies + role capacity)…")
        tasks = sched.build_schedule(tasks, start, team)
        tasks = sched.mark_critical_path(tasks)
        summary = sched.summarise(tasks, team)
        print(f"{GREEN}  {summary['start']:%d %b %Y} → {summary['end']:%d %b %Y} · "
              f"{summary['duration_working_days']} working days · "
              f"{summary['critical_task_count']} on the critical path{RESET}")

        print(f"\n{BOLD}[4/5]{RESET} Recommending a tech stack…")
        stack = stages.tech_stack(client, analysis)
        print(f"{GREEN}  {len(stack.get('recommendations', []))} layers{RESET}")

        print(f"\n{BOLD}[5/5]{RESET} Writing the plan…")
        plan_md = render_plan(analysis, breakdown, tasks, stack, summary, repairs, team)

    except (stages.StageError, sched.ScheduleError) as exc:
        sys.exit(f"{RED}{exc}{RESET}")

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(plan_md)

    with open(PLAN_JSON, "w", encoding="utf-8") as f:
        json.dump({
            "analysis": analysis,
            "breakdown": breakdown,
            "tech_stack": stack,
            "repairs": repairs,
            "summary": {k: (v.isoformat() if isinstance(v, date) else v)
                        for k, v in summary.items()},
            "tasks": [{**t, "start": t["start"].isoformat(), "end": t["end"].isoformat()}
                      for t in tasks],
        }, f, indent=2)

    words = len(plan_md.split())
    print(f"\n{BOLD}{'=' * 70}{RESET}")
    print(f"{GREEN}Done.{RESET} {summary['task_count']} tasks · "
          f"{summary['total_effort_days']} person-days · "
          f"~{summary['duration_weeks']} weeks")
    print(f"  {args.out:<20} {words} words")
    print(f"  {PLAN_JSON:<20} structured plan")
    pdf = args.out.rsplit(".", 1)[0] + ".pdf"
    print(f"\n{CYAN}Next:{RESET} python generate_report.py {args.out} {pdf}")


if __name__ == "__main__":
    main()
